<template>
  <div class="architecture">
    <h1 style="margin-top:15px;margin-bottom:25px"><p>  <b>#BlueCloudMirror</b> Architecture</p></h1>    
    <div style="margin-top:15px;">
      The game uses various key cloud technologies to demonstrate the value of a diverse, interconnected system, with both public and private cloud environments.
      
      The three main parts of #BlueCloudMirror are :
    </div>
    <div style="margin-top:15px;"></div>
    <ul>
      <li><a target="_blank" style="color:#053c9f" href="https://github.com/IBM/blue-cloud-mirror/blob/master/game/README.md"><b>Game</b></a>The core game implemented as web application and via Cloud Functions since it is only used during conferences</li>
      <li><a target="_blank" style="color:#053c9f" href="https://github.com/IBM/blue-cloud-mirror/blob/master/users/README.md"><b>Users</b></a> The user management is implemented via IBM Cloud Private to avoid having the personal data in a public cloud</li>
      <li><a target="_blank" style="color:#053c9f" href="https://github.com/IBM/blue-cloud-mirror/blob/master/scores/README.md"><b>Scores</b></a> The Highscore list is implemented via Cloud Foundry Enterprise Edition to show easy theme adoptions for different conferences</li>
    </ul>
    <div style="margin-top:15px;"></div>
    <!-- Image Map Generated by http://www.image-map.net/ -->
    <img src="diagram-overview.png" wight=600 height=470 usemap="#image-map">

    <map name="image-map">
        <area target="_blank" alt="Tensor Flow" title="Tensor Flow" href="https://www.tensorflow.org/js/" coords="10,114,10,172,86,172,85,114" shape="poly">
        <area target="_blank" alt="VUE" title="VUE" href="https://vuejs.org/" coords="13,253,10,328,86,330,86,253" shape="poly">
        <area target="_blank" alt="VUE" title="VUE" href="https://vuejs.org/" coords="11,37,10,107,86,108,86,36" shape="poly">
        <area target="_blank" alt="IBM Functions" title="IBM Functions" href="https://cloud.ibm.com/openwhisk" coords="299,109,298,164,356,165,355,107" shape="poly">
        <area target="_blank" alt="IBM Secure-Gateway" title="IBM Secure-Gateway" href="https://cloud.ibm.com/catalog/services/secure-gateway" coords="430,179,431,248,490,248,491,177" shape="poly">
        <area target="_blank" alt="IBM API Connect" title="IBM API Connect" href="https://cloud.ibm.com/catalog/services/api-connect" coords="217,176,214,327,277,327,278,177" shape="poly">
        <area target="_blank" alt="Cloud Foundry Apps" title="Cloud Foundry Apps" href="https://cloud.ibm.com/catalog?search=runtime&amp;category=compute" coords="217,334,216,391,282,391,279,333" shape="poly">
        <area target="_blank" alt="IBM Cloud Private" title="IBM Cloud Private" href="https://www.ibm.com/cloud/private" coords="461,6,463,96,592,95,590,7" shape="poly">
        <area target="_blank" alt="Kubernetes Minikube" title="Kubernetes Minikube" href="https://github.com/kubernetes/minikube" coords="596,121,561,123,564,97,595,97" shape="poly">
        <area target="_blank" alt="IBM Cloudant" title="IBM Cloudant" href="https://cloud.ibm.com/catalog/services/cloudant" coords="387,258,391,318,445,318,442,259" shape="poly">
        <area target="_blank" alt="IBM Cloudant" title="IBM Cloudant" href="https://cloud.ibm.com/catalog/services/cloudant" coords="389,109,389,167,437,168,434,108,392,109" shape="poly">
        <area target="_blank" alt="IBM APP ID" title="IBM APP ID" href="https://cloud.ibm.com/catalog/services/app-id" coords="300,35,299,98,351,98,352,36" shape="poly">
        <area target="_blank" alt="Tensor Flow" title="Tensor Flow" href="https://www.tensorflow.org/js/" coords="382,465,443,465,443,405,384,405" shape="poly">
        <area target="_blank" alt="IBM Watson Studio" title="IBM Watson Studio" href="https://dataplatform.cloud.ibm.com/" coords="290,400,290,464,360,465,359,402" shape="poly">
        <area target="_blank" alt="IBM Cloud Foundry Enterprise Environment" title="IBM Cloud Foundry Enterprise Environment" href="https://cloud.ibm.com/docs/cloud-foundry?topic=cloud-foundry-about#about" coords="282,254,280,322,374,323,371,256" shape="poly">
        <area target="_blank" alt="Couch DB" title="Couch DB" href="https://couchdb.apache.org/" coords="511,244,511,298,577,300,574,243" shape="poly">
        <area target="_blank" alt="Node.JS" title="Node.JS" href="https://nodejs.org/en/" coords="507,176,505,229,577,231,576,176" shape="poly">
        <area target="_blank" alt="IBM Cloud Object Storage" title="IBM Cloud Object Storage" href="https://cloud.ibm.com/catalog/services/cloud-object-storage" coords="209,35,210,96,274,97,272,37" shape="poly">
        <area target="_blank" alt="Lite API Management" title="Lite API Management" href="https://cloud.ibm.com/docs/api-management?topic=api-management-manage_openwhisk_apis#manage_openwhisk_apis" coords="190,110,190,165,288,167,288,111" shape="poly">
    </map>

    <div style="margin-top:15px;"></div>
    You had fun and got useful technologies insides?
    Just follow the developers of <b>#BlueCloudMirror</b> on twitter:
    <ul>
      <li><a target="_blank" style="color:#053c9f" href="https://twitter.com/nheidloff">Niklas Heidloff</a></li>
      <li><a target="_blank" style="color:#053c9f" href="https://twitter.com/tsuedbroecker">Thomas Südbröcker</a></li>
      <li><a target="_blank" style="color:#053c9f" href="https://twitter.com/harald_u">Harald Uebele</a></li>
    </ul>
    </div>
</template>

<script>
import { Component, Vue } from "vue-property-decorator";

export default {
  data(){
    return {
    imageProps: { blank: false, blankColor: '#777', width: 75, height : 75, class: 'm1' }
    }
  },
  methods: {
    onGetTheCode() {
      window.location="https://github.com/ibm/blue-cloud-mirror";
    },
    onGetAccount() {
      window.location="https://ibm.biz/nheidloff";
    },
    onTweet() {
      window.location="https://twitter.com/intent/tweet?hashtags=BlueCloudMirror,IBMDeveloper&text=Check%20out%20the%20IBM%20Cloud%20showcase%20https://blue-cloud-mirror.mybluemix.net";
    },
    onReadPattern() {
      window.location="https://developer.ibm.com/patterns/cloud-showcase-blue-mirror/";
    },
    onStartNewGame() {
      this.$router.push("start");
    }
  }
}
</script>
