<template>
  <div class="architecture">
   <h1 style="margin-top:15px;margin-bottom:25px">Explore the <b>#BlueCloudMirror</b> Architecture</h1>
   <br>
   <!-- BUTTONs -->
   <div>
    <b-row>
       <b-col>
        <b-button
          block
          v-on:click="onGetAccount"
          style="background-color: #053c9f !important;border-color:#053c9f !important;"
        >Get IBM Cloud Account</b-button>
       </b-col>
      <b-col>
        <b-button
          block
          v-on:click="onReadPattern"
          style="background-color: #FFFFFF;border-color:#030303;"
        ><font color="black">Read Pattern</font></b-button>
      </b-col>
      <b-col>
         <b-button
          block
          v-on:click="onGetTheCode"
          style="background-color: #FFFFFF;border-color:#030303;"
        ><font color="black">Get code from GitHub</font></b-button>
      </b-col>
    </b-row>
   </div>
   <div style="margin-top:15px; text-align:center;">
   <!-- Image Map Generated by http://www.image-map.net/ -->
   <img src="diagram-overview.png" wight=600 height=470 usemap="#image-map">
   <map name="image-map">
        <area target="_blank" alt="Tensor Flow" title="Tensor Flow" href="https://www.tensorflow.org/js/" coords="10,114,10,172,86,172,85,114" shape="poly">
        <area target="_blank" alt="VUE" title="VUE" href="https://vuejs.org/" coords="13,253,10,328,86,330,86,253" shape="poly">
        <area target="_blank" alt="VUE" title="VUE" href="https://vuejs.org/" coords="11,37,10,107,86,108,86,36" shape="poly">
        <area target="_blank" alt="IBM Functions" title="IBM Functions" href="https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-openwhisk_common_use_cases#openwhisk_common_use_cases" coords="299,109,298,164,356,165,355,107" shape="poly">
        <area target="_blank" alt="IBM Secure-Gateway" title="IBM Secure-Gateway" href="https://cloud.ibm.com/docs/services/SecureGateway?topic=securegateway-about-sg#about-sg" coords="430,179,431,248,490,248,491,177" shape="poly">
        <area target="_blank" alt="IBM API Connect" title="IBM API Connect" href="https://cloud.ibm.com/docs/services/apiconnect?topic=apiconnect-about_apic_overview#about_apic_overview" coords="217,176,214,327,277,327,278,177" shape="poly">
        <area target="_blank" alt="Cloud Foundry Apps" title="Cloud Foundry Apps" href="https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-howwork#howwork" coords="217,334,216,391,282,391,279,333" shape="poly">
        <area target="_blank" alt="IBM Cloud Private" title="IBM Cloud Private" href="https://www.ibm.com/cloud/private" coords="461,6,463,96,592,95,590,7" shape="poly">
        <area target="_blank" alt="Kubernetes Minikube" title="Kubernetes Minikube" href="https://github.com/kubernetes/minikube" coords="596,121,561,123,564,97,595,97" shape="poly">
        <area target="_blank" alt="IBM Cloudant" title="IBM Cloudant" href="https://cloud.ibm.com/docs/services/Cloudant?topic=cloudant-ibm-cloudant-basics#ibm-cloudant-basics" coords="387,258,391,318,445,318,442,259" shape="poly">
        <area target="_blank" alt="IBM Cloudant" title="IBM Cloudant" href="https://cloud.ibm.com/docs/services/Cloudant?topic=cloudant-ibm-cloudant-basics#ibm-cloudant-basics" coords="389,109,389,167,437,168,434,108,392,109" shape="poly">
        <area target="_blank" alt="IBM APP ID" title="IBM APP ID" href="https://cloud.ibm.com/docs/services/appid?topic=appid-about#about" coords="300,35,299,98,351,98,352,36" shape="poly">
        <area target="_blank" alt="Tensor Flow" title="Tensor Flow" href="https://www.tensorflow.org/js/" coords="382,465,443,465,443,405,384,405" shape="poly">
        <area target="_blank" alt="IBM Watson Studio" title="IBM Watson Studio" href="https://dataplatform.cloud.ibm.com/" coords="290,400,290,464,360,465,359,402" shape="poly">
        <area target="_blank" alt="IBM Cloud Foundry Enterprise Environment" title="IBM Cloud Foundry Enterprise Environment" href="https://cloud.ibm.com/docs/cloud-foundry?topic=cloud-foundry-about#about" coords="282,254,280,322,374,323,371,256" shape="poly">
        <area target="_blank" alt="Couch DB" title="Couch DB" href="https://couchdb.apache.org/" coords="511,244,511,298,577,300,574,243" shape="poly">
        <area target="_blank" alt="Node.JS" title="Node.JS" href="https://nodejs.org/en/" coords="507,176,505,229,577,231,576,176" shape="poly">
        <area target="_blank" alt="IBM Cloud Object Storage" title="IBM Cloud Object Storage" href="https://cloud.ibm.com/catalog/services/cloud-object-storage" coords="209,35,210,96,274,97,272,37" shape="poly">
        <area target="_blank" alt="Lite API Management" title="Lite API Management" href="https://cloud.ibm.com/docs/api-management?topic=api-management-manage_openwhisk_apis#manage_openwhisk_apis" coords="190,110,190,165,288,167,288,111" shape="poly">
    </map>
    </div>
    <hr>
    <!-- YouTube -->
    <div style="margin-top:15px;">
    Watch the webinar to understand how the components are used and interact.
    <div style="margin-top:15px;"></div>
    <b-row>
      <b-col>
        <center><iframe
          v-for="data in youtubeJSON"
          v-bind:key="data.width"
          v-bind:width="data.width"
          v-bind:height="data.height"
          v-bind:src="data.src"
          v-bind:frameborder="data.frameborder"
          v-bind:allow="data.allow"
          allowfullscreen
        >
        </iframe></center>
      </b-col>
      <b-col>
          Select your start:
          <div style="margin-top:5px;"></div>
          <b-link v-on:click="onYouTubeDemo"><li>Game demo [5:03 mins]</li></b-link>
          <div style="margin-top:5px;"></div>
          <b-link v-on:click="onYouTubeMotivation"><li>Motivation to build #BlueCloudMirror [7:05 mins]</li></b-link>
          <div style="margin-top:5px;"></div>
          <b-link v-on:click="onYouTubeArchitecture"><li>Architecture and four main components [8:30 mins]</li></b-link>
          <div style="margin-top:5px;"></div>
          <b-link v-on:click="onYouTubeSetup"><li>Setup #BlueCloudMirror in five minutes [13:45 mins]</li></b-link>
          <div style="margin-top:5px;"></div> 
          <b-link v-on:click="onYouTubeTensorFlow"><li>Three TensorFlow.js visual recognition models [14:37 mins]</li></b-link>
          <div style="margin-top:5px;"></div>
          <b-link v-on:click="onYouTubeCoreGame"><li>Architecture of the core game [21:50 mins]</li></b-link>
          <div style="margin-top:5px;"></div>
          <b-link v-on:click="onYouTubeUsers"><li>Architecture of the users service [27:20 mins]</li></b-link>
          <div style="margin-top:5px;"></div>
          <b-link v-on:click="onYouTubeScores"><li>Architecture of the scores service [35:38 mins]</li></b-link> 
          <div style="margin-top:5px;"></div>        
      </b-col>
    </b-row>
    </div>
    <!-- Follow -->
    <div style="margin-top:15px;"></div>
    <div>
    You had fun and got useful technologies insides?<br>
    Just get in touch with the developers of <b>#BlueCloudMirror</b> on twitter:
    <div style="margin-top:15px;"></div>
      <ul>
        <li><a target="_blank" style="color:#053c9f" href="https://twitter.com/nheidloff">Niklas Heidloff</a></li>
        <li><a target="_blank" style="color:#053c9f" href="https://twitter.com/tsuedbroecker">Thomas Südbröcker</a></li>
        <li><a target="_blank" style="color:#053c9f" href="https://twitter.com/harald_u">Harald Uebele</a></li>
      </ul>
    </div>
  </div>
</template>

<script>
import { Component, Vue } from "vue-property-decorator";
var youtubedata = {
  "0":{
    width:"853",
    height:"480",
    src:"https://www.youtube.com/embed/Z4wU03JnEcU?start=303",
    frameborder:"0",
    allow:"accelerometer; autoplay; encrypted-media; gyroscope;  picture-in-picture",
    allowfullscreen:""
  }
};

export default {
  data: function () {
    return { 
      youtubeJSON: youtubedata
    }
  },
  methods: {
    onYouTubeDemo() {
      youtubedata[0].src="https://www.youtube.com/embed/Z4wU03JnEcU?start=303"
    },
    onYouTubeMotivation() {
      youtubedata[0].src="https://www.youtube.com/embed/Z4wU03JnEcU?start=425"
    },
    onYouTubeArchitecture() {
      youtubedata[0].src="https://www.youtube.com/embed/Z4wU03JnEcU?start=510"
    },
    onYouTubeSetup() {
      youtubedata[0].src="https://www.youtube.com/embed/Z4wU03JnEcU?start=825"
    },
    onYouTubeTensorFlow() {
      youtubedata[0].src="https://www.youtube.com/embed/Z4wU03JnEcU?start=877"
    },
    onYouTubeCoreGame() {
      youtubedata[0].src="https://www.youtube.com/embed/Z4wU03JnEcU?start=1310"
    },
    onYouTubeUsers() {
      youtubedata[0].src="https://www.youtube.com/embed/Z4wU03JnEcU?start=1640"
    },
    onYouTubeScores() {
      youtubedata[0].src="https://www.youtube.com/embed/Z4wU03JnEcU?start=2138"
    },
    onGetTheCode() {
      window.location="https://github.com/ibm/blue-cloud-mirror";
    },
    onGetAccount() {
      window.location="https://ibm.biz/nheidloff";
    },
    onReadPattern() {
      window.location="https://developer.ibm.com/patterns/cloud-showcase-blue-mirror/";
    }
  }
}
</script>
