<template>
  <div class="maparchitecture" id="maparchitecture">
   <div style="margin-top:15px; text-align:center;">
   <!-- Image Map Generated by http://www.image-map.net/ -->
   <img v-for="data in imagedata"
        v-bind:key="data.src"
        v-bind:src="data.src"
        v-bind:wight="data.wight"
        v-bind:height="data.height"
        v-bind:usemap="data.usemap">
   <map name="custom-image-map">
        <area 
        v-for="data in mapdata"
        v-bind:key="data.key"
        v-bind:target="data.target"
        v-bind:alt="data.alt"
        v-bind:title="data.title"
        v-bind:href="data.href"
        v-bind:coords="data.coords"
        v-bind:shape="data.shape">
    </map>
    </div>
  </div>
</template>

<script>
import { Component, Vue } from "vue-property-decorator";

var mapdata = {
  "0":{
    key:0,
    target:'_blank',
    alt:'Tensor Flow',
    title:'Tensor Flow',
    href:"https://www.tensorflow.org/js/",
    coords:"10,114,10,172,86,172,86,114",
    shape:"poly"
  },
  "1":{
    key:1,
    target:'_blank',
    alt:'VUE',
    title:'VUE',
    href:"https://vuejs.org/",
    coords:"13,253,13,328,86,328,86,253",
    shape:"poly"
  },
  "2":{
    key:2,
    target:'_blank',
    alt:'IBM Functions',
    title:'IBM Functions',
    href:"https://cloud.ibm.com/docs/openwhisk?topic=cloud-functions-openwhisk_common_use_cases#openwhisk_common_use_cases",
    coords:"298,108,298,164,354,164,354,108",
    shape:"poly"
  },
  "3":{
    key:3,
    target:'_blank',
    alt:'IBM Secure-Gateway',
    title:'IBM Secure-Gateway',
    href:"https://cloud.ibm.com/docs/services/SecureGateway?topic=securegateway-about-sg#about-sg",
    coords:"430,176,431,248,490,248,490,176",
    shape:"poly"
  },
  "4":{
    key:4,
    target:'_blank',
    alt:"IBM API Connect",
    title:"IBM API Connect",
    href:"https://cloud.ibm.com/docs/services/apiconnect?topic=apiconnect-about_apic_overview#about_apic_overview",
    coords:"217,176,214,327,278,327,278,176",
    shape:"poly"
  },
  "5":{
    key:5,
    target:'_blank',
    alt:"Cloud Foundry Apps",
    title:"Cloud Foundry Apps",
    href:"https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-howwork#howworkw",
    coords:"216,334,216,390,282,390,282,334",
    shape:"poly"
  },
  "6":{
    key:6,
    target:'_blank',
    alt:"IBM Cloud Private",
    title:"IBM Cloud Private",
    href:"https://www.ibm.com/cloud/private",
    coords:"460,8,460,96,590,96,590,8",
    shape:"poly"
  },
  "7":{
    key:7,
    target:'_blank',
    alt:"Kubernetes Minikube",
    title:"Kubernetes Minikube",
    href:"https://github.com/kubernetes/minikube",
    coords:"594,122,560,122,560,98,594,98",
    shape:"poly"
  },
  "8":{
    key:8,
    target:'_blank',
    alt:"IBM Cloudant",
    title:"IBM Cloudant",
    href:"https://cloud.ibm.com/docs/services/Cloudant?topic=cloudant-ibm-cloudant-basics#ibm-cloudant-basics",
    coords:"386,258,386,318,442,318,442,258",
    shape:"poly"
  },
  "9":{
    key:9,
    target:'_blank',
    alt:"IBM Cloudant",
    title:"IBM Cloudant",
    href:"https://cloud.ibm.com/docs/services/Cloudant?topic=cloudant-ibm-cloudant-basics#ibm-cloudant-basics",
    coords:"388,108,388,168,434,168,434,108,388,108",
    shape:"poly"
  },
  "10":{
    key:10,
    target:'_blank',
    alt:"IBM APP ID",
    title:"IBM APP ID",
    href:"https://cloud.ibm.com/docs/services/appid?topic=appid-about#about",
    coords:"300,34,300,98,350,98,350,34",
    shape:"poly"
  },
  "11":{
    key:11,
    target:'_blank',
    alt:'Tensor Flow',
    title:'Tensor Flow',
    href:"https://cloud.ibm.com/docs/services/appid?topic=appid-about#about",
    coords:"382,464,442,464,442,406,382,406",
    shape:"poly"
  },
  "12":{
    key:12,
    target:'_blank',
    alt:'Tensor Flow',
    title:'Tensor Flow',
    href:"https://cloud.ibm.com/docs/services/appid?topic=appid-about#about",
    coords:"382,464,442,464,442,406,382,406",
    shape:"poly"
  },
  "13":{
    key:13,
    target:'_blank',
    alt:"IBM Watson Studio",
    title:"IBM Watson Studio",
    href:"https://dataplatform.cloud.ibm.com/docs/content/wsj/getting-started/welcome-main.html?context=analytics",
    coords:"290,400,290,464,358,464,358,400",
    shape:"poly"
  },
  "14":{
    key:14,
    target:'_blank',
    alt:"IBM Cloud Foundry Enterprise Environment",
    title:"IBM Cloud Foundry Enterprise Environment",
    href:"https://cloud.ibm.com/docs/cloud-foundry?topic=cloud-foundry-about#about",
    coords:"280,254,280,322,372,323,372,254",
    shape:"poly"
  },
  "15":{
    key:15,
    target:'_blank',
    alt:"Couch DB",
    title:"Couch DB",
    href:"https://couchdb.apache.org/",
    coords:"510,244,510,298,574,300,574,244",
    shape:"poly"
  },
  "16":{
    key:16,
    target:'_blank',
    alt:"Node.JS",
    title:"Node.JS",
    href:"https://nodejs.org/en/",
    coords:"504,176,504,228,576,228,576,176",
    shape:"poly"
  },
  "17":{
    key:17,
    target:'_blank',
    alt:"IBM Cloud Object Storage",
    title:"IBM Cloud Object Storage",
    href:"https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-about-ibm-cloud-object-storage#about-ibm-cloud-object-storage",
    coords:"208,36,208,96,272,98,272,36",
    shape:"poly"
  },
  "18":{
    key:18,
    target:'_blank',
    alt:"Lite API Management",
    title:"Lite API Management",
    href:"https://cloud.ibm.com/docs/api-management?topic=api-management-manage_openwhisk_apis#manage_openwhisk_apis",
    coords:"190,110,190,164,288,164,288,110",
    shape:"poly"
  },
  "19":{
    key:19,
    target:'_blank',
    alt:"VUE",
    title:"VUE",
    href:"https://vuejs.org/",
    coords:"10,36,10,108,86,108,86,36",
    shape:"poly"
  }
};
var mapdataLength = 20;
var imagedata  = {"0":{
     src:"diagram-overview-1160x900.bmp",
     wightBase:600,
     heightBase:470,
     usemap:"#custom-image-map",
     wight:900,
     height:705
}};

export default {
  name: 'mapArchitecture',
  data: function () {
    return { 
      mapdata: mapdata,
      imagedata: imagedata
    }
  },
  mounted() {
    this.scaleImage();
  },
  methods: {
    scaleImage(){
      var factor = (parseFloat(imagedata[0].height)/parseFloat(imagedata[0].heightBase));
      var i = 0;
      
      // extract coords
      for (i = 0; i < mapdataLength ; i++){
        var list = mapdata[i].coords.split(',');
        var temp = mapdata[i];
        var coords = "";
        var j = 0;
        var k = 0;
        
        // scale coords
        for (j = 0; j < 8 ; j++){  
          list[j] = Math.round(parseFloat(list[j])*factor);
        }

        // build coords
        for (k = 0; k < 8 ; k++){
          if(k==0){
            coords = ""+parseInt(list[k])+"";
          } else {
            coords = coords + ","+ parseInt(list[k]);
          }
        }
        
        // build mapdata
        mapdata[i] = { target:temp.target,
                       alt:temp.alt,
                       title:temp.title,
                       href:temp.href,
                       coords:coords,
                       shape:temp.shape
                     };
      }
    }
  }
}
</script>
